LISTAS_DE_PRUEBA = {
    "Test_1": [
        "6 Esp 32 Modulo Wifi- Bluetooth 30 Pines",
        "6 Sensor BME680 (I2C)",
        "6 Resistencias 4.7kΩ (Pack)",
        "6 Capacitor Electrolítico 470µF 16V",
        "12 Fuente de Poder 5V 2A",
        "12 Protoboard 400 Puntos",
        "12 Placa Perforada Universal",
        "18 Regleta Tira De Pines Macho 40 Pines",
        "18 Regleta Tira De Pines Hembra 40 Pines",
        "12 Cables Jumper Dupont (Pack 40 surtido)",
        "12 Cable Micro USB Datos",
        "4 Sensor Rango Laser ToF VL53L1X",
        "2 Bomba de Agua Periférica 220V AC",
        "2 Módulo Relé 1 Canal 5v Optoacoplado",
        "2 Sensor Nivel De Agua Liquido Boya",
        "2 Terminal Block 2 pines KF301",
        "2 Cables Jumper Dupont (Pack 40 M-M/M-H/H-H)",
        "2 Caja de Paso PVC",
    ],
    "Test_2": [
        "4 Diodo rectificador 1N5408",
        "4 Varistor 14D431K",
        "1 Baquelita Perforada 20x30cm",
        "8 Bornero Terminal con tornillo",
    ],
    "Test_3": [
        "2 LED ROJOS",
        "2 LEDS VERDES",
        "2 LEDS AMARILLOS",
        "10 RESISTENCIAS 330 OHMS",
        "2 PULSADOR/BOTON 2 PINES",
        "1 BUZZER",
        "5 JUMPERS MACHO-HEMBRA",
        "5 JUMPERS MACHO-MACHO",
        "1 BROCHE PORTA PILA 9V",
        "1 BATERIA 9V",
        "1 PROTOBOARD PEQUEÑO",
    ],
    "Test_4": [
        "8 100uF Capacitor",
        "8 100kΩ Resistor",
        "8 10kΩ Resistor",
        "3 620Ω Resistor",
        "3 LED",
    ],
    "Test_5": [
        "1 Módulo ESP32",
        "1 Pantalla TFT SPI 3.2",
        "1 Módulo USB a UART CP2102",
        "1 Zócalo ZIF 40 pines",
        "1 Pulsador con retención 8x8mm",
        "2 Transistor S8050",
        "1 Capacitor tantalio 10 uF",
        "1 Capacitor tantalio 100 uF",
        "1 Capacitor 1 uF",
        "1 Capacitor 10 uF",
        "1 Capacitor 100 nF",
        "1 Resistencia 12 kΩ",
        "1 Memoria flash 25Q128 QuadSPI",
    ],
}
